### PR TITLE
Rework fidelityAPI using Playwright

### PR DESCRIPTION
**Pull request by kennyboy106**
Same code as previous pull request but with a few fixes

Added 2FA support
Added extended hours trading support
Fixed holdings functionality
Cleaned up code using playwright and added lots of comments

Tested:
Buying 2 stocks at a time
Selling 2 stocks at a time
Holdings

### CODE REVIEW

**Comment by kennyboy106** [comment]
I'd love to continue contributing!
If you'd like me to help with some development projects and want to include me in the conversation, my discord is the same as my github username

**Comment by vue551** [comment]
i know this is still in the works tried to test  Traceback (most recent call last):
  File "C:\Users\neten\OneDrive\Documents\kusg\fidelityAPI.py", line 516, in fidelity_init
    step_1, step_2 = fidelity_browser.login(account[0], account[1], account[2])
                                                                    ~~~~~~~^^^
IndexError: list index out of range this is the error i got

**Comment by kennyboy106** [comment]
> i know this is still in the works tried to test Traceback (most recent call last): File "C:\Users\neten\OneDrive\Documents\kusg\fidelityAPI.py", line 516, in fidelity_init step_1, step_2 = fidelity_browser.login(account[0], account[1], account[2]) ~~~~~~~^^^ IndexError: list index out of range this is the error i got

See the .env.exanple file for fidelity credentials

**Comment by kennyboy106** [comment]
Found a bug when selling, more work needed. I'll resume working on this on 9/25

**Comment by kennyboy106** [comment]
Buying and selling seems to be fixed now

**Comment by kennyboy106** [comment]
Hey Matthew, I was hoping to keep the fidelity automation class free from and custom functions so that I can try publishing the library for general use. 
Can you move the printanddiscord call in __init__ outside of the class? 
Maybe we just throw a general exception in the __init__ and catch it back in the fidelity_run function

**Comment by NelsonDane** [comment]
This has been working really well for me, well done!

Only feedback would be to remove the "Summary of holdings," since the other brokers don't have that and if we were going to add it we'd do it in the helperAPI print holdings function.

**Comment by kennyboy106** [comment]
Sounds good, I won't be able to make the change until later tonight or tomorrow, traveling all day today

**Comment by kennyboy106** [comment]
Those last two errors are minor. I think the code is fine now

**Pull request merged**
