### PR TITLE
Robinhood login

### PR DESCRIPTION
**Pull request by 0jc1**
Made changes to robinhood login: 
- Enabled store_session so that the session is saved to a pickle file for future logins
- Set expiresIn to 30 days instead of the the default 1 day

This fixes the issue of needing to enter a 2fa code every time the bot restarts. It worked when I tested.

### CODE REVIEW

**Comment by matthew55** [comment]
https://github.com/jmfernandes/robin_stocks/issues/287

I am a bit hesitant to set the expire time to 30 days, the issue above shows that it seems like we would expect closer to 7 days. However, if the session expires the user will just login again so it is no big deal. I like this PR.

Also, if you follow [these steps](https://github.com/NelsonDane/auto-rsa/blob/main/guides/robinhoodSetup.md) you will *NEVER* have to type in an SMS code! 🫨 

Thank you for this PR, if I can confirm the owner did not have save_session to False for any particular reason this will get merged.

**Comment by NelsonDane** [comment]
I used to have `store_session=True`, but it was disabled for a few reasons:
1. Unfortunately, `robin_stocks` doesn't allow us to specify where to save the pickle file
2. [This issue](https://github.com/jmfernandes/robin_stocks/issues/202) has come up with users before, which has caused confusion when they change their env and it keeps using the wrong account (because of the pickle file stored who knows where)

While I appreciate the PR, this is the reasoning for keeping `store_session=False`. If `robin_stocks` updates and allows us to specify the pickle path, then we should definitely revisit this in the future. I'm OK with 30 days since when you login to the RH website they have a box for staying signed in for 30 days you can tick. If either of you feel differently or have thoughts please share @0jc1 @matthew55

**Comment by 0jc1** [comment]
I've set store_session back to false. As for expiresIn, it should keep the session from expiring after a day, but this not well documented. The best way around session expiring may be to add a re-auth method and use mfa code.

**Comment by NelsonDane** [comment]
Yeah, it's not extremely clear if `expires_in` helps or not. I would argue the best way to keep a session from expiring is to just [follow this guide](https://github.com/NelsonDane/auto-rsa/blob/main/guides/robinhoodSetup.md) so you don't have to worry about sessions expiring at all!

**Comment by ImNotOssy** [comment]
> Yeah, it's not extremely clear if `expires_in` helps or not. I would argue the best way to keep a session from expiring is to just [follow this guide](https://github.com/NelsonDane/auto-rsa/blob/main/guides/robinhoodSetup.md) so you don't have to worry about sessions expiring at all!

I also feel like this is the best option, that's why I used it for SoFi.

**Comment by NelsonDane** [comment]
Hey @0jc1 , sorry for the confusion!

I've been doing a lot of digging in the Robinhood API, and finally fixed a long-running issue. [The solution](https://github.com/NelsonDane/auto-rsa/pull/338) does involve your original pull request code:
```python
store_session=True,
expiresIn=86400 * 30, # 30 days
```
(30 days is fine IMO because there's a box for that on robinhood.com)

Once again, sorry for the conflicting info, but if you update your PR with this code then I'll approve. I definitely don't want to deny your PR and then implement the same thing a few days later 😆

**Comment by 0jc1** [comment]
Glad I could help with this. :smiley:

**Review by NelsonDane — APPROVED** [review]

**Pull request merged**
