### PR TITLE
fyi - fennel account notice

### PR DESCRIPTION
**Pull request by braydio**
account notice
had to take out some potentially identifying info thx

### CODE REVIEW

**Comment by braydio** [comment]
Hey guy(s) just wanted to give you a heads up, someone I know got the attached email notice from Fennel. I don't have much more details but feel free to shoot me an email/discord etc. if there's anything you're curious about this I could try and find out

**Comment by braydio** [comment]
oh also feel free to close this pr whenever, wasn't really sure how else to contact

**Comment by matthew55** [comment]
Thanks for the info.

**Comment by NelsonDane** [comment]
Thanks for the notice @braydio. I've seen this email off and on over the past half-year or so, but haven't ever gotten anything myself. I try to keep the API as close to the Android app as I can but of course there's no guarantees that things like this won't happen

**Comment by braydio** [comment]
Sure thing, in the trading group I’m in we were talking it through but it
doesn’t even seem to be against Fennel’s ToS from what we could discern
about how the script works. The person who received the email just took off
his fennel credentials and they gave him back access to his accounts.

**Pull request closed without merging**
