### PR TITLE
Login improvements error dismiss fix.

### PR DESCRIPTION
**Pull request by MaxxRK**
- Added a loop for the login so that it will retry the login page three times and then raise and exception.
           - I have seen this not load the login page correctly a few times. I hope this will help. So far in testing it does.
- Fixed the error dismiss on a preview, and added the text from the error to the print out.

### CODE REVIEW

**Comment by hungerp1** [comment]
Just tested it out and it resolved my login issues using the discord bot.

**Comment by vue551** [comment]
> Just tested it out and it resolved my login issues using the discord bot.

  it doesnt click palce order when it puts ticker

**Comment by MaxxRK** [comment]
> > Just tested it out and it resolved my login issues using the discord bot.
> 
> it doesnt click palce order when it puts ticker

I am not sure what you mean by this. Does it have an error of any kind?

**Comment by MaxxRK** [comment]
> > Just tested it out and it resolved my login issues using the discord bot.
> 
> it doesnt click palce order when it puts ticker

Try it again. I found the problem

**Comment by MaxxRK** [comment]
> Just tested it out and it resolved my login issues using the discord bot.

Did you try any sell orders? Would you try to sell a stock that you do not have so it will try to dismiss the pop-ups.

**Review by matthew55 — APPROVED** [review]
Looks good to me and tested on Docker too

**Pull request merged**
