### PR TITLE
Switch to my Pypi api

### PR DESCRIPTION
**Pull request by kennyboy106**
Need some light testing here.
@MaxxRK  told me about some issues with using playwright stealth so I tested a dry buy order on chase. Testers, please test chase to ensure the dependencies from fidelity don't mess with it.

Updated the readme to give myself credit for fidelity.

Also fixed the problem with getAccountInfo. This was due to a new UI update in the positions tab of fidelity.

### CODE REVIEW

**Comment by braydio** [comment]
Nice, maybe I can get this guy running on my raspberry pi now. Will update- thanks!

**Comment by NelsonDane** [comment]
Remember to update the `.env.example` as well @kennyboy106

**Comment by kennyboy106** [comment]
> Remember to update the `.env.example` as well @kennyboy106

That was updated a while ago so it already shows the 2fa for fidelity example.

**Comment by kennyboy106** [comment]
Been testing this for the past few days, working without issue thus far

**Review by NelsonDane — APPROVED** [review]
Works for me. Thanks @kennyboy106 !

**Pull request merged**
