### PR TITLE
Update sofiAPI.py

### PR DESCRIPTION
**Pull request by ImNotOssy**
Increased Sleep Time on SoFi due to it being TOO FAST XD

### CODE REVIEW

**Review by matthew55 — APPROVED** [review]
Looks good, bud

**Comment by namyamankad** [comment]
image

im having trouble using the bot. im not very good at this coding stuff lmao. but im using it in pycharm. i inputed my login without a totp and the image i provided is what i get. anyway to fix this? any help is appreaciated.

**Comment by ImNotOssy** [comment]
Are you on the main branch?

**Comment by namyamankad** [comment]
im not sure. is this the main branch? thats where im editing the code. do i need to do playwrite? i dont have that
image

**Comment by ImNotOssy** [comment]
> i only need help with sofi. everything else works fine. so restarting wouldn't make sense

Try 
Git pull main 
or something, not sure how the command works

**Comment by namyamankad** [comment]
ok. was able to fix it. had some changes in sofi apy. and to stash it. then was able to do git pull origin main. I had to update my main branch thing cause it was couple months old. and now im able to type in the command !rsa holdings sofi and stuff is happing but getting this error now. 
image

**Comment by ImNotOssy** [comment]
> ok. was able to fix it. had some changes in sofi apy. and to stash it. then was able to do git pull origin main. I had to update my main branch thing cause it was couple months old. and now im able to type in the command !rsa holdings sofi and stuff is happing but getting this error now. image

consider sponsoring @NelsonDane in order to get access to the discord server community where we can help better.

**Comment by namyamankad** [comment]
@NelsonDane sponsored but did it one time by accident. I sped thru it and then saw Discord access is for monthly only.Anyway, i can still get access to the discord?

**Pull request merged**
