### PR TITLE
WebullAPI.py Margin Acct Protections

### PR DESCRIPTION
**Pull request by Nohealz**
Adding functionality to check for Webull margin account day trades and prevent from purchasing if already at 3.

Could be improved by looking at how many tickers were entered for trading.

### CODE REVIEW

**Comment by Nohealz** [comment]
This doesn't work quite yet.

**Comment by NelsonDane** [comment]
Next time just set it as a draft instead of closing if it's not ready @Nohealz

**Comment by Nohealz** [comment]
> Next time just set it as a draft instead of closing if it's not ready @Nohealz

I'm not seeing where to do that.

**Comment by Nohealz** [comment]
Webull already has PDT protections built in.

**Pull request closed without merging**
