### PR TITLE
Update autoRSA.py (Which brokers are called with different commands)

### PR DESCRIPTION
**Pull request by Nohealz**
1. Vanguard: This broker is blocking new RSA buys for everyone in my network. I still think it's beneficial to utilize the bot for specific VG orders but it doesn't make sense to include it in the 'all' command. Removing it from this section still allows you access to the VanguardAPI.
2. Robinhood: Not truly day 1 like the rest of them. Takes an extra day.

I am consistently adding 'NOT VG' and 'NOT RH' to the command.

### CODE REVIEW

**Comment by NelsonDane** [comment]
After contemplating and discussing this, here's what I think is best:
* VG should remain on `all`, since the purpose of `all` is to run all brokers that you have defined in your `.env` file. If you want to exclude it, then either remove it from the `.env` file or continue to `not vg` the command.
* I think you're right, RH should be removed from `day1` since it's not truly a day 1 broker. Perhaps a new class like `fast` could be added which is `day1 + RH`.

**Comment by Nohealz** [comment]
Ok it is ready for review.

**Comment by Nohealz** [comment]
If I messed something up let me know. A few of us ready to use the functionality.

**Review by NelsonDane — CHANGES_REQUESTED** [review]
Sorry for the delay, I've been gone a bit. Made a small change, but the rest of your code looks fine. Good not modifying the global brokers variables in case they're used somewhere else

**Comment by NelsonDane** [comment]
Also update this branch with the newest changes from `main` @Nohealz

**Comment by Nohealz** [comment]
I am not sure how to correct this but git has just been spinning on my latest push for days now. Do I just scrap this pull request and start a new one?

**Comment by NelsonDane** [comment]
> I am not sure how to correct this but git has just been spinning on my latest push for days now. Do I just scrap this pull request and start a new one?

I'm guessing that means there's Merge Conflicts (😭). So what you need to do is checkout main locally, then pull all the newest changes, and then merge main into your branch. Then fix any conflicts that arise, commit, then push back here, and then it should work and be up to date @Nohealz

**Pull request closed without merging**
