### PR TITLE
Execution price to .csv

### PR DESCRIPTION
**Pull request by braydio**
Several people in the group where I learned about this script were talking about functionality to update their records with order execution fills, so I was wondering if this was something that you'd want to include in the main script. 

This is a fairly straightforward implementation, it just adds save_execution_price() as a csv file. Ideally this functionality would be added to the other APIs as well. Thanks!

### CODE REVIEW

**Comment by ImNotOssy** [comment]
ive been thinking about this, should be a lot easier once all account holdings and buy/sell prints are set to the same formats. but id love to track what ive bought and what i havent on a google sheet.

**Comment by braydio** [comment]
right, and if you haven't been - lemme tell you this is not fun to track manually lol. idea was to have a print of execution prices in a csv that someone could pull into another script or open with excel to log. but if things are moving towards having a uniform buy/sell/holdings print then it might make sense to wait until that's wrapped up before tackling order logging.

**Comment by NelsonDane** [comment]
A few thoughts on this in no particular order:
* You should add an option to turn this on/off (default to off), since for example, I wouldn't want it saving CSVs if it's running on a server somewhere.
* Most of the APIs have a way to retrieve info about a specific order you made, which would be more accurate. So you'd place the order, get the order ID, then search for the executed price for that specific order ID. Sometimes the price can move quickly or be all over the place, so placing an order and then getting the stock's current price could give back much different numbers.
* I'm not sure how you want to handle this, but sometimes orders don't fill right away, which means there would be no order executed price.

Another idea if you don't want to wait for this to be merged/support all brokers is to create your own wrapper script that calls my script during the execution.

**Comment by braydio** [comment]
So just kinda trying out some ideas, trying to find one that has the least impact on the active files. started building out ordersAPI as (I think) a sort of wrapper but still working out some of the logic for it to be able to call the local APIs for order history. mainly pulled it in for version history logging (& tips/feedback if anyone has free time)

**Comment by braydio** [comment]
Is this something you think would be good to get started on implementing? Or wait until the all the prints are uniform first?

I think making a class for the order details in the helper file could be an easy way for this to be iterated across brokerages, maybe creating a third argument to pass to fun_run() that would pull order details for the day? RH api is the only one i've been working with and it looks like they don't have a method to filter the order search parameters, so pulling all order info and then filtering that down to orders for current day seems to be a reasonable way to sort out the orders you want from the massive order history it pulls.

Lmk if you have any thoughts on this, or want to shelf it for now

**Comment by ImNotOssy** [comment]
This is an incredible task that I don't think we will be working on soon.

**Pull request closed without merging**
