### PR TITLE
Add SoFi Support

### PR DESCRIPTION
**Pull request by NelsonDane**
In collab with @EClinick. Very WIP

### CODE REVIEW

**Comment by Nohealz** [comment]
Anything I can do to help this along?

**Review by ImNotOssy — APPROVED** [review]

**Comment by NelsonDane** [comment]
Lol bro approved code that doesn't even work

**Comment by ImNotOssy** [comment]
> Lol bro approved code that doesn't even work

lol i didnt mean to approve it, i was messing around with something. I approve the work although good stuff.

**Comment by NelsonDane** [comment]
This is old and outdated and replaced by other PRs (see https://github.com/NelsonDane/auto-rsa/pull/314)

**Comment by EClinick** [comment]
Ya, I tried using multiple forms of selenium using its undetected chrome driver, but Cloudflare's antibot detection seemed to be integrated into SOFI. I tested multiple IPs and some worked, I tried it in Greece and it worked but when I tried my home IP it got flagged.

**Comment by Thesyjaga** [comment]
@EClinick does your sofi api work?

**Pull request closed without merging**
