### PR TITLE
Fix Multiple Robinhood Accounts and Save Cookies Cache

### PR DESCRIPTION
**Pull request by NelsonDane**
See `robin_stocks` PR: https://github.com/jmfernandes/robin_stocks/pull/490

Saves Robinhood cookies to `./creds/`, and adds a `login_with_cache` function to refresh the accounts. Previously, the accounts would overwrite each other (an issue with the `robin_stocks` library, but one way too big to debug right now) which would occur in the last account being the only working one. The function uses the saved cookies to avoid hitting the Robinhood API, and is more of a way to tell the API to "switch" to that account/cache.

Since Joint accounts show up under both logins, don't add a duplicate when it's found under multiple logins.

Depends on and implements: https://github.com/NelsonDane/auto-rsa/pull/332

### CODE REVIEW

**Comment by NelsonDane** [comment]
ToDo:
- [ ] Update README with note about tokens. If env is changed around, it will keep using old account info (since cache is still valid), so old files in `creds` folder need to be cleared by user.

**Comment by NelsonDane** [comment]
Hmm, I'm only testing with 2 logins but make sure you're up to date (at this time it's `6a97f6b`). One other person has confirmed this working with 2 logins as well.

**Comment by braydio** [comment]
Hey nice! Seems to work perfect with 3 accounts too, thanks

**Review by matthew55 — APPROVED** [review]
Works extremely well from what I have heard, and I have no issues with my 1 account so this is approved.

**Pull request merged**
