### PR TITLE
Update tradierAPI.py to Limit orders

### PR DESCRIPTION
**Pull request by Nohealz**
Changed to Limit buys at ask, and sells at bid.

### CODE REVIEW

**Comment by thezlehman** [comment]
Just a heads up Traider sent this out: Tradier Brokerage is reaching out today regarding reverse split round-up trading. Beginning 11/5/2024, Tradier Brokerage will no longer permit this trading activity. Customers who previously engaged in this trading will no longer be permitted to open new positions in these securities going forward.

**Comment by ImNotOssy** [comment]
> Just a heads up Traider sent this out: Tradier Brokerage is reaching out today regarding reverse split round-up trading. Beginning 11/5/2024, Tradier Brokerage will no longer permit this trading activity. Customers who previously engaged in this trading will no longer be permitted to open new positions in these securities going forward.

Thanks but we are already aware

**Comment by NelsonDane** [comment]
Is this still needed @Nohealz

**Comment by Nohealz** [comment]
> Is this still needed @Nohealz

With Tradier going bye bye. I don't think it really matters.

**Pull request closed without merging**
