### PR TITLE
bbae pro support

### PR DESCRIPTION
**Pull request by ImNotOssy**
about time?

very limited use, can only log in, view holdings, and buy

no selling only SMS login available

requires this library https://github.com/ImNotOssy/BBAE_investing_API

### CODE REVIEW

**Comment by ImNotOssy** [comment]
@matthew55 there's a bug I forgot to fox last night. The command in-between is missing

"bbae",
"chase",

**Comment by ImNotOssy** [comment]
In the autoRSA.py

**Comment by NelsonDane** [comment]
Remember to add the bbae invest api to requirements.txt @ImNotOssy

**Comment by ImNotOssy** [comment]
> Remember to add the bbae invest api to requirements.txt @ImNotOssy 

I don't know how to make it a pip install type of thing.

**Pull request closed without merging**
