### PR TITLE
Rework fidelity driver

### PR DESCRIPTION
**Pull request by kennyboy106**
Recreate the fidelityAPI using playwright. 
This codes fixes the holdings feature. Previously, the holdings command did not display correct price values for holdings or shares owned. 
This code is also much easier to read and fix, thanks to playwrights codegen and autowaiting, and should be more resilient to changes in the website. Less css selectors are used and more text-based searching is used for interacting with the webpage.

**Added support for TOTP secrets!**
Fidelity allows you to enable authenticator codes and will use that instead of text based codes. 

This has been tested with:
Buying and selling
Holdings
Terminal mode
Discord docker

The code format follows the chaseAPI format.

### CODE REVIEW

**Comment by PZES** [comment]
This is a massivs pr u shuld probably only have the fidelity canges on the pr

**Comment by PZES** [comment]
I don't see any changes here, this just update the dev branch to main

**Comment by kennyboy106** [comment]
Im trying to clean up my push since its affecting many files but not showing any changes in most of the files

**Comment by PZES** [comment]
just change the pr to push to main

**Comment by kennyboy106** [comment]
Well, there's all the changes lol
Not a simple pr

**Comment by matthew55** [comment]
Thank you for your interest in contributing to this project. This would be quite a large PR with a lot of testing if we are to do this so let me make some initial thoughts I have.

1. All the file permissions have been changed from 100644 ->100755. This needs to be reverted back because We do not need all these files to be executable.
2. I would like to take advantage of this PR to make Fidelity more of a hybrid broker meaning we use Playwright to obtain cookies and other necessary information and then use those cookies in requests in order to try to make as many operations request based as possible. This is what the [Charles Schwab API](https://github.com/itsjafer/schwab-api) does. If you are not up to this, do not worry, I would be willing to try figuring this out on my end.

**Comment by kennyboy106** [comment]
Ill look into changing the permissions on those.
Id need some more information for that feature. Ill also have to go look at Charles Schwab API to see how that works.

There are still some issues in the playwright code when executing trading that I am trying to solve right now.

**Pull request closed without merging**
