### PR TITLE
Add Wells Fargo

### PR DESCRIPTION
**Pull request by PZES**

### CODE REVIEW

**Comment by PZES** [comment]
WIP

**Comment by NelsonDane** [comment]
I'd recommend looking at the `fidelityAPI.py` since that's also implemented with Selenium. For example, when initializing the `driver`, don't do it in the global namespace but instead do it like [Fidelity](https://github.com/NelsonDane/auto-rsa/blob/90515b893b4a9fe64557d7a2e65c17251ab82851/fidelityAPI.py#L72). That way if Docker is used it will use the argument from the initialization, vs being hardcoded to False.

**Comment by PZES** [comment]
TODO
Fix manual sleeps
Fix to zoom automatically
Detect the incomplete transaction when switch account

**Comment by NelsonDane** [comment]
Any reason this was closed? Seemed like good progress was being made @PZES

**Comment by PZES** [comment]
It got closed when u moved the repo, still working on it will make new pr when its mostly done

**Comment by NelsonDane** [comment]
Awesome, sorry about that!

**Pull request closed without merging**
